version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /mnt/containers/gitea/container-data/data:/data
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
    networks:
      - supervision-nw
      - reverseproxy-nw
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - /mnt/containers/gitea/container-data/data:/data
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - "8086:8086"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    networks:
      - supervision-nw
      - reverseproxy-nw

networks:
  supervision-nw:
  reverseproxy-nw:
    external: true
