version: '3'
services:
  web:
    image: krosand/pico-glx:latest 
    ports:
      - "8080:80"  
    restart: always 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
