FROM nginx:alpine
COPY ./src/ /usr/share/nginx/html/
#RUN chown -R nginx:nginx /usr/share/nginx/html
# Assurer les permissions correctes sur les fichiers
#RUN chmod -R 755 /usr/share/nginx/html
EXPOSE 80

