version: '3'

services:
  web:
    image: krosand/pico-glx:preprod
    container_name: pp-gaulix-fr
    ports:
      - "8080:8080"  
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /mnt/containers/pp.gaulix.fr/data:/usr/share/nginx/html 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - reverseproxy-nw

networks:
  reverseproxy-nw:
    external: true
