version: '3'
services:
  mosquitto-prod:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto-prod
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /mnt/containers/mosquitto/config:/mosquitto/config
      - /mnt/containers/mosquitto/data:/mosquitto/data
      - /mnt/containers/mosquitto/log:/mosquitto/log
      - ./mosquitto.conf:/mnt/containers/mosquitto/config/mosquitto.conf
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
  node-red:
    image: nodered/node-red:2.2.3-12
    container_name: nodered-prod
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /mnt/containers/nodered/data:/data
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - "1880:1880"
    #env_file:
     # ./node-red.env
    restart: unless-stopped
    depends_on:
      - mosquitto-prod
    networks:
      - reverseproxy-nw
networks:
  reverseproxy-nw:
    external: true
