version: '3'
services:
  mosquitto-prod:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto-prod
    ports:
      - "1883:1883"
      - "9001:9001"
    user: "${UID}:${GID}"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /mnt/containers/mosquitto/config:/mosquitto/config
      - /mnt/containers/mosquitto/data:/mosquitto/data
      - /mnt/containers/mosquitto/log:/mosquitto/log
      #- /mnt/containers/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      #- /mnt/containers/mosquitto/data/passwords.txt:/mosquitto/data/passwords.txt
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
  node-red:
    image: nodered/node-red:3.0.2-18
    container_name: nodered-prod
    user: "${UID}:${GID}"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /mnt/containers/nodered/data:/data
      - /mnt/containers/nodered/data/settings.js:/data
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    environment:
      - NODE_RED_CREDENTIAL_SECRET='$2b$08$YkII2fmzgWbNiouH84MuzOqz9P2fJyJTzDzgPLMMrRoI.vK1sqhA6'
    ports:
      - "1880:1880"
    #env_file:
     # ./node-red.env
    restart: unless-stopped
    depends_on:
      - mosquitto-prod
    networks:
      - reverseproxy-nw
networks:
  reverseproxy-nw:
    external: true
