name: CI/CD Pipeline Prod glx

on:
  push:
    branches:
      - main  # Se déclenche sur la branche 'main'
  pull_request:
    branches:
      - main  # Se déclenche lors des PR vers 'main'
  tag:
    branches:
      - '*'  # Se déclenche lors des tags

jobs:
  build-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set the Docker image version
      id: version
      run: |
        if [ ! -z "${{ github.ref_type }}" ] && [ "${{ github.ref_type }}" == "tag" ]; then
          echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
        fi

    - name: Build and push Docker image for production
      run: |
        cd gaulix.fr
        docker buildx build --platform linux/amd64,linux/arm64 \
        -t krosand/pico-glx:${{ env.IMAGE_TAG }} --push .

    - name: Tag and push the 'latest' Docker image
      run: |
        docker tag krosand/pico-glx:${{ env.IMAGE_TAG }} krosand/pico-glx:latest
        docker push krosand/pico-glx:latest
