name: CI/CD Pipeline pp glx

on:
  push:
    branches:
      - preprod  # Se déclenche lors des pushes sur la branche 'preprod'
    tags:
      - '*'  # Se déclenche également lors des pushes de tags
  pull_request:
    branches:
      - preprod  # Se déclenche lors des PR vers 'preprod'

jobs:
  build-preprod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set the Docker image version
      id: version
      run: |
        if [ ! -z "${{ github.ref_type }}" ] && [ "${{ github.ref_type }}" == "tag" ]; then
          echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=preprod-${{ github.sha }}" >> $GITHUB_ENV
        fi

    - name: Build and push Docker image for preprod
      run: |
        cd gaulix.fr
        docker buildx build --platform linux/amd64,linux/arm64 \
        -t krosand/pico-glx:${{ env.IMAGE_TAG }} --push .
